site_name: 长日将尽
theme: windmill

nav:
    - Main page: index.md
    - Solutions: 
        - Codeforces contests: empty.md
        - Codeforces Gym: empty.md
        - Codeforces Problemset: empty.md
    - Library: 
        - Geometry: Library/Geometry.md